CC=gcc
CFLAGS=-lm -Wall

DEPS= tPonto.h tCirculo.h tRetangulo.h tTriangulo.h

OBJ=tPonto.o tCirculo.o tRetangulo.o tTriangulo.o main.o

%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

ponto: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS)
	echo "Compilado!"

clean:
	rm -rf *.o main